version: 2.1
orbs:
  ruby: circleci/ruby@2.0.0 # https://circleci.com/orbs/registry/orb/circleci/ruby

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.4
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
  test:
    docker:
      - image: cimg/ruby:3.1.4-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          RAILS_ENV: test
      - image: cimg/postgres:14.2
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: postgres
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Wait for DB
          command: 'dockerize -wait tcp://localhost:5432 -timeout 1m'
      - run:
          name: Set up database
          command: 'bundle exec rails db:create db:schema:load --trace'
      - ruby/rspec-test
  gravity:
    docker:
      - image: cimg/ruby:3.1.4-node
        environment:
          RAILS_ENV: test
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Precompile assets
          command: 'bundle exec rails assets:precompile --trace'
      - run:
          name: 'Run Gravity'
          command: 'npx gravityci "public"'
workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - gravity:
          requires:
            - build
          filters:
            branches:
              ignore:
                - main
